#!/bin/sh
set -e
ARX=..
export ARX
TMPF=/tmp/testmc.$$
../bin/db2rdb -r <../src/mcmessag.rdb |
../bin/db2rdb | sed '1,2d' >$TMPF
sed '1,2d' ../src/mcmessag.rdb |
diff $TMPF -
../bin/mc2wks <formula.mc |
tee formula.wks |
../bin/mc2wks -r |
../bin/mc -p | diff formula.out - | wc -l >$TMPF
echo 4 | diff -w $TMPF -
rm $TMPF
