/* $Id: mcolor.h,v 1.2 1995/02/26 17:04:33 axel Rel $
 */

#define TEXTCOLOR A_NORMAL
#define EOFCOLOR A_BOLD
#define ERRORCOLOR A_BLINK
#define VALUECOLOR A_NORMAL
#define FORMULACOLOR A_NORMAL
#define STRINGCOLOR A_NORMAL
#define BLANKCOLOR A_NORMAL
#define HEADERCOLOR A_REVERSE
#define CURHEADERCOLOR A_BOLD
#define HIGHLIGHTCOLOR A_REVERSE
#define HIGHLIGHTERRORCOLOR (A_REVERSE|A_BLINK)
#define MARKCOLOR A_REVERSE
#define AUTOCALCCOLOR A_REVERSE
#define FORMDISPLAYCOLOR A_REVERSE
#define MESSAGECOLOR (A_BOLD|A_BLINK)
#define PROMPTCOLOR A_BOLD
#define INPUTCOLOR A_REVERSE
#define COMMANDCOLOR A_UNDERLINE
#define CELLCONTENTSCOLOR A_NORMAL
#define	BOLDCOLOR A_BOLD
#define	ITALICOLOR A_UNDERLINE

/*
#define BLACK 0
#define BLUE 1
#define GREEN 2
#define CYAN 3
#define RED 4
#define MAGENTA 5
#define BROWN 6
#define LIGHTGRAY 7
#define DARKGRAY 8
#define LIGHTBLUE 9
#define LIGHTGREEN 10
#define LIGHTCYAN 11
#define LIGHTRED 12
#define LIGHTMAGENTA 13
#define YELLOW 14
#define WHITE 15
#define BLINK 128
*/
