remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: MacroCALC
url: https://mc.freakout.de
show_downloads: true
show_edgerelease: false
show_archrelease: true
show_footer: false
logo: /assets/logo.jpg
edgerelease: "10.50"
latestrel: "10.50"
archrelease: "10.40"
